# Generated by Django 4.0.5 on 2022-12-26 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('local_video_file', models.FileField(default='', upload_to='local_videos')),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_label', models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People'), ('er_tech', 'Technology'), ('other', 'Other')], max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('link', embed_video.fields.EmbedVideoField()),
                ('image', models.ImageField(upload_to='img')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_label', models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People'), ('er_tech', 'Technology'), ('other', 'Other')], max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
