# Generated by Django 4.0.5 on 2023-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_quote',
            field=models.CharField(default='Your post quote here', max_length=20, null=True),
        ),
    ]
