# Generated by Django 4.0.5 on 2023-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_post_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_quote',
            field=models.CharField(default='Quote', max_length=15, null=True),
        ),
    ]
